workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 120
    environment:
      android_signing:
        - tikboost_pro_key
      vars:
        PACKAGE_NAME: "com.example.tikboost_pro"
        BUNDLE_ID: "com.example.tikboost_pro"
    triggering:
      events:
        - push
      branch:
        include:
          - main
          - master
    scripts:
      - name: Set up local properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release \
            --build-number=$(($(date +%s) / 60)) \
            --build-name=1.0.0
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true
